= REST Endpoints
:imagesdir: ../assets/images

Some RESTful endpoints are available for basic connection management.

NOTE: The `Content-Type` of the request and response is `application/json`.

[options="header, %autowidth"]
[cols="2,1,3"]
|===
| Resource
| Method
| Description

| `/plugin/nutanix/\{alias}/clusters`
| GET
| Returns the associated clusters for a configured nutanix with alias connection.

| `/plugin/nutanix/\{alias}/hosts`
| GET
| Returns the associated hosts for a configured nutanix with alias connection.

| `/plugin/nutanix/\{alias}/vms`
| GET
| Returns the associated vms for a configured nutanix with alias connection.

| `/plugin/nutanix/connections`
| GET
| Returns the list of configured connections.

| `/plugin/nutanix/connections`
| POST
| Adds a new connection.

| `/plugin/nutanix/connections/\{alias}`
| PUT
| Updates a configured connection.

| `/plugin/nutanix/connections/\{alias}`
| GET
| Validates a configured connection.

|===

== Examples

=== Retrieve vms for a given prism connection

.Request
[source, console]
----
curl -X GET -u admin:admin http://localhost:8980/opennms/rest/plugin/nutanix/prismAlias/vms
----

.Response
[source, json]
----
[
  {
    "enterpriseId": "78a92010-9085-4d9c-9537-92eab2522697",
    "id": 342,
    "networkId": 1,
    "gatewayPoolId": 2,
    "bastionState": "UNCONFIGURED",
    "alertsEnabled": true,
    "operatorAlertsEnabled": true,
    "name": "RALEIGH_LAB",
    "domain": "rdulab",
    "accountNumber": "RDU-foo",
    "description": "",
    "address": "PO Box 362",
    "city": "Apex",
    "state": "North Carolina",
    "zip": "27502",
    "country": "US",
    "latitude": 35.770000,
    "longitude": -78.640000,
    "timezone": "America/New_York",
    "locale": "en-US"
  },
  {
    "enterpriseId": "f9adcb3e-21be-451d-997f-fd21e429129c",
    "id": 213,
    "networkId": 1,
    "gatewayPoolId": 2,
    "bastionState": "UNCONFIGURED",
    "alertsEnabled": true,
    "operatorAlertsEnabled": true,
    "name": "OTTAWA_LAB",
    "domain": "yowlab",
    "accountNumber": "YOW-bar",
    "description": "",
    "address": "300 March Rd, Suite 600",
    "city": "Kanata",
    "state": "Ontario",
    "zip": "K2K 2E2",
    "country": "CA",
    "latitude": 45.300000,
    "longitude": -75.916000,
    "timezone": "America/Toronto",
    "locale": "en-US"
  }
]
----

=== Retrieve a list of configured connections

.Request
[source, console]
----
curl -u admin:admin http://localhost:8980/opennms/rest/plugin/nutanix/connections
----

.Response
[source, json]
----
[
  {
    "alias": "aPartnerAlias",
    "prismUrl": "https://something-somewhere.nutanix.net/"
  },
  {
    "alias": "aCustomerAlias",
    "prismUrl": "https://something-somewhere.nutanix.net/"
  }
]
----

=== Add a new connection

.Request
[source, console]
----
curl -H "Content-type: application/json" -X POST -u admin:admin http://localhost:8980/opennms/rest/plugin/nutanix/connections --data '{"alias":"anotherAlias","prismUrl":"https://something-somewhere.nutanix.net","apiKey":"juKdsndSJnsjsdH3KnedejS3kNk3mndsfks3.sad8asdkhasd8asdSDSDFhkasd8asdhasd7k32l32kKkjbsdNS01ZGRhNGRlNGU2N2IiLCJleHAiOjE2OTY1NDExODYwMDAsInV1aWQiOiJV1aWQiOiI0MDUwMDJiNS01YjQ4sInR5cCI6IkpXVCQ3OTYtOWRiOS03NmRhODUxMGMyYjEiLCJOjE2OTY1NDExODYwMDAsInV1aWQiOdsJdsSjkSDlJLJ"}'
----

.Response
[source, text]
----
Connection successfully added
----

=== Update a connection

.Request
[source, console]
----
curl -H "Content-type: application/json" -X PUT -u admin:admin http://localhost:8980/opennms/rest/plugin/nutanix/connections/anotherAlias --data '{"prismUrl":"https://something-somewhere.nutanix.net","apiKey":"juKdsndSJnsjsdH3KnedejS3kNk3mndsfks3.sad8asdkhasd8asdSDSDFhkasd8asdhasd7k32l32kKkjbsdNS01ZGRhNGRlNGU2N2IiLCJleHAiOjE2OTY1NDExODYwMDAsInV1aWQiOiJV1aWQiOiI0MDUwMDJiNS01YjQ4sInR5cCI6IkpXVCQ3OTYtOWRiOS03NmRhODUxMGMyYjEiLCJOjE2OTY1NDExODYwMDAsInV1aWQiOdsJdsSjkSDlJLJ"}'
----

.Response
[source, text]
----
Connection successfully updated
----

=== Validate a configured connection

.Request
[source, console]
----
curl -X GET -u admin:admin http://localhost:8980/opennms/rest/plugin/nutanix/connections/anotherAlias
----

.Response
[source, json]
----
{
"alias": "anotherAlias",
"nutanixUrl": "https://something-somewhere.nutanix.net",
"valid": true
}
----
